# Generated by Django 6.0 on 2025-12-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('finish', models.DateTimeField(null=True)),
                ('reason', models.TextField(max_length=512)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='devices.device')),
            ],
        ),
    ]
