# Generated by Django 6.0 on 2025-12-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='reason',
            field=models.CharField(choices=[('periodic_maintenance', 'Periodic Maintenance'), ('hardware_failure', 'Hardware Failure'), ('system_update', 'System Update')], max_length=512),
        ),
    ]
