# Generated by Django 6.0 on 2025-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0002_alter_downtime_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
