# Generated by Django 6.0 on 2025-12-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0003_downtime_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
