# Generated by Django 6.0 on 2025-12-20 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0004_alter_downtime_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='finish',
            field=models.DateTimeField(blank=None, null=True),
        ),
        migrations.AlterField(
            model_name='downtime',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
