# Generated by Django 6.0 on 2025-12-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0005_alter_downtime_finish_alter_downtime_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
