# Generated by Django 6.0 on 2025-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0006_alter_downtime_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
