# Generated by Django 6.0 on 2025-12-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtimes', '0007_alter_downtime_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
