# Generated by Django 6.0 on 2025-12-16 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='supervisor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
