# Generated by Django 6.0 on 2025-12-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_device_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(default=0)),
                ('max_value', models.FloatField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='devices.device')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='devices.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('situation', models.CharField(choices=[('above_max', 'Above Max'), ('below_min', 'Below Min')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='devices.device')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicetype')),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thresholds.threshold')),
            ],
        ),
    ]
